### ISSUE TITLE
Definiëren wat er in het menu komt

### ISSUE THREAD

**Issue by nvh** [tomasharkema/GameOfHive#41]
- [x] Donate link #44 
- [x] Credits #9 
- [x] Bee video #8 / Foto van een bij
- [ ] Fertility instellingen #29 
- [ ] Steppen in plaats van play #34 
- [ ] Screengrab #33 
- [ ] Reset to previous state #31 
- [ ] Snelheid van iteraties #20 
- [ ] Template opslaan #13 
- [x] Vaste Template selecteren #10
- [ ] Increase grid size #11 
- [x] About
- [x] Saved states selecteren

**Comment by nvh** [comment]
Gerelateerd aan #16 en #17

**Comment by nvh** [comment]
Ik heb hier geïnventariseerd wat we allemaal in het menu zouden kunnen stoppen, nu moeten we nog beslissen wat er daadwerkelijk in komt

**Comment by nvh** [comment]
Discuss! @tomasharkema @tacovollmer @GFunkloostar
